real horas,valorHora,salario,extras

Inicio

     escriba "Ingrese horas trabajadas: "
     lea horas

     escriba "Ingrese valor por hora: "
     lea valorHora

     si horas > 40 entonces
        extras <- horas - 40
        salario <- (40 * valorHora) + (extras * valorHora * 1.5)
     sino
        salario <- horas * valorHora
     fin si

     escriba "El salario total es: ", salario

Fin