entero num1,num2,num3,mayor

Inicio

     escriba "Ingrese el primer número"
     lea num1

     escriba "Ingrese el segundo número"
     lea num2

     escriba "Ingrese el tercer número"
     lea num3

     si (num1 > num2) Y (num1 > num3) entonces
        mayor <- num1
     sino
     si (num2 > num1) Y (num2 > num3) entonces
        mayor <- num2
     sino
        mayor <- num3
     fin si
     fin si

     escriba "El mayor es: ", mayor

Fin