real nota1,nota2,nota3,promedio

Inicio

     escriba "Ingrese la primera nota: "
     lea nota1

     escriba "Ingrese la segunda nota: "
     lea nota2

     escriba "Ingrese la tercera nota: "
     lea nota3

       promedio <- (nota1 + nota2 + nota3) / 3

     escriba "El promedio es: ", promedio

     si promedio > 3.5 entonces
     escriba " El estudiante APROBÓ "
     sino
     escriba " El estudiante REPROBÓ "
     fin si

Fin